<?php

/**
 * @file
 * Primary module hooks for Company Info module.
 */

/**
 * Implements hook_theme().
 */
function company_info_theme($existing, $type, $theme, $path) {
    return [
        'company_info_template' => [
            'variables' => [
                'name' => '',
                'address' => '',
                'number' => '',
                'email' => '',
                'description' => '',
                'facebook' => '',
                'linkedin' => '',
                'twitter' => '',
            ]
        ]
    ];
}