company_info:
  name: 'Corporate Solutions'
  address: Here
  phone_number: '1234'
  email: email@csolutions.lv
  description: 'The place I work'
  facebook_link: ''
  linkedin_link: ''
  twitter_link: ''
