<?php

/**
 * @file
 * Primary module hooks for Resume module.
 */

/**
 * Implements hook_theme().
 */
// function resume_theme($existing, $type, $theme, $path) {
//     return [
//         'company_info_template' => [
//             'variables' => [
//                 'name' => '',
//                 'address' => '',
//                 'number' => '',
//                 'email' => '',
//                 'description' => '',
//                 'facebook' => '',
//                 'linkedin' => '',
//                 'twitter' => '',
//             ]
//         ]
//     ];
// }